### ISSUE TITLE
Note regarding trademark

### ISSUE THREAD

**Issue by SamB** [FortAwesome/phoenix-app#4]
Just thought I would warn/remind you that Firefox used to be called Phoenix; see: <https://en.wikipedia.org/wiki/Firefox_early_version_history#Phoenix_and_Firebird>

Apparently Phoenix Technologies (the BIOS people) had a browser in their BIOS or something, so I guess there's less scope for confusion here, but I just thought it would be polite to point out that the name had been a problem for an open source project before ...

**Comment by robmadole** [comment]
This is based on https://www.phoenixframework.org/. Thanks for the head up.
